/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function getSteamPath(): string
export interface AppInfo {
  appid: number
  gamename: string
}
export function getAppInfo(): Array<AppInfo>
